version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    ports:
      - 9200:9200
    expose:
      - 9300
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - "xpack.security.enabled=false"


  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
